name: Rail-Fire
version: '${version}'
main: craftschemers.railfire.RailFirePlugin
api-version: 1.19
description: Rail Fire Minigame
commands:
  start:
    description: Start the RailFire game.
    usage: /start
